apiVersion: v1
kind: Service
metadata:
  name: skoro-ai
  namespace: sk-team-10
spec:
  selector:
    app: skoro-ai
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
