apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: sk-team-10
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    - protocol: TCP
      port: 50000
      targetPort: 50000
  type: ClusterIP
