apiVersion: apps/v1
kind: Deployment
metadata:
  name: skoro-frontend
  namespace: sk-team-10
  labels:
    app: skoro-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: skoro-frontend
  template:
    metadata:
      labels:
        app: skoro-frontend
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
        prometheus.io/path: '/actuator/prometheus'
    spec:
      serviceAccountName: default
      containers:
        - name: frontend
          image: amdp-registry.skala-ai.com/skala25a/skoro-frontend:1.0.0-12
          imagePullPolicy: Always
          ports:
            - containerPort: 80