apiVersion: v1
kind: Service
metadata:
  name: skoro-backend
  namespace: sk-team-10
spec:
  selector:
    app: skoro-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
